node(params.node) {

    def tool = new Tool(this)

    stage('CleanUp') {
        fileOperations([folderDeleteOperation('')])
    }

    stage('Git') {
        git branch: "${params.branch}", credentialsId: "${params.credentials}", url: "${params.framework_url}"
    }

    stage('Gradle') {

        dir(tool.getRoot()) {
            tool.createJar()
            tool.runJar()
        }
    }

}

class Tool {

    def pipe
    def mainClass = 'com.tool.automation.core.runner.ToolTestRunner'
    def root = ''

    Tool(def pipe) {
        this.pipe = pipe
    }

    void createJar() {
        pipe.bat 'gradle shadowJar'
    }

    String runJar() {
        String paramString = "-url \"${pipe.params.application_url}\" -excel \"test-input/${pipe.params.suite}/${pipe.params.case}.xlsx\""

        if (pipe.params.api) {
            paramString = paramString + " -api"
        }
        pipe.bat "java -cp at_tool-1.0.jar ${mainClass} ${paramString}"
    }
}

