node(params.node) {

    def tool = new Tool(this)

    stage('CleanUp') {
        fileOperations([folderDeleteOperation('')])
    }

    stage('Git') {
        git branch: "${params.branch}", credentialsId: "${params.credentials}", url: "${params.framework_url}"
    }

    stage('Gradle') {

        dir(tool.getRoot()) {
            tool.createJar()
            tool.runJar()
        }
    }

}

class Tool {

    def pipe
    def mainClass = 'com.tool.automation.core.runner.ToolTestRunner'
    def root = ''

    Tool(def pipe) {
        this.pipe = pipe
    }

    void createJar() {
        pipe.bat 'gradle shadowJar'
    }

    String runJar() {
        String paramString = ["-Durl=\"${pipe.params.application_url}\""
                , "-Dexcel=\"test-input/${pipe.params.suite}/${pipe.params.case}.xlsx\""
                , "-Drp.endpoint=\"${pipe.params.rp_url}\""
                , "-Drp.project=\"${pipe.params.rp_project}\""
                , "-Drp.uuid=\"${pipe.params.rp_uuid}\""
                , "-Dtool.url=\"${pipe.params.tool_url}\""
                , "-DcaseNumber=${pipe.params.case_number}"].join(" ")

        if (pipe.params.api) {
            paramString = paramString.concat(" -Dapi=false")
        }
        pipe.bat "java ${paramString} -cp at_tool-1.0.jar ${mainClass}"
    }
}

